### ISSUE TITLE
Pembentukan tim pengelola website iprakom dan resourcenya

### ISSUE THREAD

**Issue by ekojs** [iprakomindonesia/iprakom#3]
Mungkin perlu juga untuk dirumuskan siapa saja pengelola website resmi iprakom dan segala resource yang ada di github ini. Agar website ini lebih terarah dan berkembang.

**Comment by tamami** [comment]
hmm.. ok juga itu.. cuma saya belum kepikiran program-nya apa..

**Comment by yasnum** [comment]
Tambah seru nih...

Pada tanggal 5 Jul 2017 8.37 PM, "P. Tamami" <notifications@github.com>
menulis:

**Comment by ekojs** [comment]
Jadi gimana nih masukannya pak @tamami, @yasnum , @camagenta ? :D

**Comment by yasnum** [comment]
Langsung dibentuk aja, sambil liat perkembangannya, semakin banyak
pertimbangan gak jalan2.

Pada tanggal 21 Jul 2017 11.04 AM, "Eko Junaidi Salam" <
notifications@github.com> menulis:

**Comment by tamami** [comment]
ok.. setuju.. ini saya close saja ya.. keputusannya kan jalan saja dulu sambil nanti ketemu web officialnya..
